name = "index"
main = "src/worker.js"
compatibility_date = "2023-07-06"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "ENV"
id = "8e81edcb9a724148a796a9f8da1e5958"
preview_id = "cd438d0e1a4a4ee6915cfad327e86944"
